version: 0.0
os: linux

files:
  - source: /script/*
    destination: /home/ubuntu/node/angellist-node.js-app/
    overwrite: true
file_exists_behavior: OVERWRITE
files:
  - source: /docker-compose.yml
    destination: /home/ubuntu/node/angellist-node.js-app/
    overwrite: true
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/node/angellist-node.js-app/scripts/app_start.sh
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777
    type : 
      - file

hooks:

  BeforeInstall:

  AfterInstall:

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 120
      runas: ubuntu
