version: 0.0
os: linux

files:
  - source: docker-compose.yml
    destination: /home/ubuntu/node/angellist-node.js-app/docker-compose.yml
    overwrite: true
    file_exists_behavior: OVERWRITE

  - source: scripts/
    destination: /home/ubuntu/node/angellist-node.js-app/scripts/
    overwrite: true
    file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/node/angellist-node.js-app/scripts/app_start.sh
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777
    type:
      - file

hooks:
  BeforeInstall:
    # Commands to run before installing files (optional)
  
  AfterInstall:
    # Commands to run after files are installed (optional)

  ApplicationStart:
    - location: /home/ubuntu/node/angellist-node.js-app/scripts/app_start.sh
      timeout: 120
      runas: ubuntu
