name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag node.js-anglelist-github-action:$(date +%s)
    - name: push image into docker-hub
      run: docker tag node.js-anglelist-github-action:$(date +%s) sushil26/node.js-anglelist-github-action:$(date +%s)
