name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/node.js-app-anglelist:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/node.js-app-anglelist:latest

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_USER: ubuntu
        EC2_HOST: ${{ secrets.EC2_HOST }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        
        # Create a temporary directory on EC2 for deployment files
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "mkdir -p ~/deployment"
        
        # Copy docker-compose.yml to the EC2 instance
        scp -o StrictHostKeyChecking=no -i key.pem docker-compose.yml $EC2_USER@$EC2_HOST:~/deployment/docker-compose.yml
        
        # Connect to the EC2 instance and run deployment commands
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd ~/deployment
          sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          sudo docker-compose -f docker-compose.yml pull
          sudo docker-compose -f docker-compose.yml up -d
          sudo docker logout
        EOF
